### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/footloose#83]
While the end to end tests are awesome they make for slow progress and can miss nuisances that are hard to reach. Also, coverage reports are awesome.

I'm order to do that some of the thirds party depencenies will have to be extracted and injected into footloose. 

This issues is here to track this process through several smaller prs that will steadily clean up the depency on docker for example. 

Incidentally that will allow us to more easily swap it out when footloose wants to switch to CRI in #54.

**Comment by dlespiau** [comment]
I'm obviously all for unit tests but they may need mocking the world to test the container related features. I'm sure you have read `tests/README.md` as you fixed a typo there :) I guess the tests are still to long to run with the `-short` go test option?

A note is that we can produce coverage reports when running end to end tests by producing a specially instrumented `footloose` and merging reports from all the test runs. I wrote up a long thing about that: https://damien.lespiau.name/posts/2017-01-29-building-and-using-coverage-instrumented-programs-with-go/

Another note related to the CRI backend is that we'll still want to keep the docker backend along with the CRI one I think so we can still offer `footloose` directly on top of docker.

A final note :) I often make the choice of improving tests and infrastructure instead of improving the software features. Sometimes that's the right thing to do, sometimes it's not very pragmatic and end up forgetting about making the thing better. There's definitely a balance there, just wouldn't want you to spend a lot of time writing tests and getting bored :)

**Comment by Skarlso** [comment]
I never get bored of writing tests. :) Usually they end up improving the code a lot. Especially for Go, because I end up refactoring dependencies on third party components. :)

Cool, cool. I agree with all that you said btw. :) Cool stuff!

**Comment by dlespiau** [comment]
I've split the code coverage part in its own issue in #102. Issues should have actionable things to do and this one is a bit too general. I'm closing it as is, but if you have a more precise task around unit testing (eg. "such or such function/file needs unit tests"), please do open a new issue!

**Comment by Skarlso** [comment]
Okay \o
