### ISSUE TITLE
brew formula

### ISSUE THREAD

**Issue by developer-guy** [weaveworks/footloose#87]
please add formula for footloose to brew

**Comment by dlespiau** [comment]
Hi! That sounds like a good idea, I'll try to do it for the next release.

**Comment by dlespiau** [comment]
I've merged the brew support into master and `footloose` should be release to the [tap repo](https://github.com/weaveworks/homebrew-tap) when tagging the next version. This issue is left open to:

- Ensure it all works when we release 0.3.0
- Add a note in the README.md about using `brew` when releasing 0.3.0

**Comment by developer-guy** [comment]
thanks @dlespiau for your great work !

**Comment by dlespiau** [comment]
0.3.0 is out and the homebrew formula has been uploaded by the release CI. Hopefully working :)
